// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'ActionButton': typeof import("../components/ActionButton.vue")['default'],
    'BoxCard': typeof import("../components/BoxCard.vue")['default'],
    'BoxCardInput': typeof import("../components/BoxCardInput.vue")['default'],
    'BoxEditForm': typeof import("../components/BoxEditForm.vue")['default'],
    'LinkButton': typeof import("../components/LinkButton.vue")['default'],
    'MenuItem': typeof import("../components/MenuItem.vue")['default'],
    'OverviewCard': typeof import("../components/OverviewCard.vue")['default'],
    'QuestionCard': typeof import("../components/QuestionCard.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyActionButton': typeof import("../components/ActionButton.vue")['default'],
    'LazyBoxCard': typeof import("../components/BoxCard.vue")['default'],
    'LazyBoxCardInput': typeof import("../components/BoxCardInput.vue")['default'],
    'LazyBoxEditForm': typeof import("../components/BoxEditForm.vue")['default'],
    'LazyLinkButton': typeof import("../components/LinkButton.vue")['default'],
    'LazyMenuItem': typeof import("../components/MenuItem.vue")['default'],
    'LazyOverviewCard': typeof import("../components/OverviewCard.vue")['default'],
    'LazyQuestionCard': typeof import("../components/QuestionCard.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const ActionButton: typeof import("../components/ActionButton.vue")['default']
export const BoxCard: typeof import("../components/BoxCard.vue")['default']
export const BoxCardInput: typeof import("../components/BoxCardInput.vue")['default']
export const BoxEditForm: typeof import("../components/BoxEditForm.vue")['default']
export const LinkButton: typeof import("../components/LinkButton.vue")['default']
export const MenuItem: typeof import("../components/MenuItem.vue")['default']
export const OverviewCard: typeof import("../components/OverviewCard.vue")['default']
export const QuestionCard: typeof import("../components/QuestionCard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyActionButton: typeof import("../components/ActionButton.vue")['default']
export const LazyBoxCard: typeof import("../components/BoxCard.vue")['default']
export const LazyBoxCardInput: typeof import("../components/BoxCardInput.vue")['default']
export const LazyBoxEditForm: typeof import("../components/BoxEditForm.vue")['default']
export const LazyLinkButton: typeof import("../components/LinkButton.vue")['default']
export const LazyMenuItem: typeof import("../components/MenuItem.vue")['default']
export const LazyOverviewCard: typeof import("../components/OverviewCard.vue")['default']
export const LazyQuestionCard: typeof import("../components/QuestionCard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
